/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VercelSetupRouteImport } from './routes/vercel-setup'
import { Route as MallRouteImport } from './routes/mall'
import { Route as IndexRouteImport } from './routes/index'

const VercelSetupRoute = VercelSetupRouteImport.update({
  id: '/vercel-setup',
  path: '/vercel-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MallRoute = MallRouteImport.update({
  id: '/mall',
  path: '/mall',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mall': typeof MallRoute
  '/vercel-setup': typeof VercelSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mall': typeof MallRoute
  '/vercel-setup': typeof VercelSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mall': typeof MallRoute
  '/vercel-setup': typeof VercelSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mall' | '/vercel-setup'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mall' | '/vercel-setup'
  id: '__root__' | '/' | '/mall' | '/vercel-setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MallRoute: typeof MallRoute
  VercelSetupRoute: typeof VercelSetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vercel-setup': {
      id: '/vercel-setup'
      path: '/vercel-setup'
      fullPath: '/vercel-setup'
      preLoaderRoute: typeof VercelSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mall': {
      id: '/mall'
      path: '/mall'
      fullPath: '/mall'
      preLoaderRoute: typeof MallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MallRoute: MallRoute,
  VercelSetupRoute: VercelSetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
